### ISSUE TITLE
Complete draft of design doc

### ISSUE THREAD

**Issue by turtlefarmer** [turtlefarmer/codeu_project_2017#1]

**Comment by iamgreggarcia** [comment]
Still working on this. We still need to add some of our other, non-core feature ideas into the document, as well as break down our core features into approx. 3-5 smaller units of work.

**Comment by turtlefarmer** [comment]
The non-core features aren't a priority for the design doc, but definitely do the break-down before you start seriously coding.

**Comment by turtlefarmer** [comment]
Looks good.  :+1:
