### ISSUE TITLE
Messages not displayed when user joins conversation

### ISSUE THREAD

**Issue by rshar1** [turtlefarmer/codeu_project_2017#50]
In Gui 2, when a user joins a conversation, the messages are not displayed in the message panel. It would be nice if when conversation changes, the messages load up.

**Comment by noramyer** [comment]
You mean like when a new user joins an existing conversation, have messages pull up?

**Comment by rshar1** [comment]
yep

**Comment by rshar1** [comment]
The message panel is staying empty. Is that intentional?

**Comment by noramyer** [comment]
Not intentional, youre right it should pull up previous messages

**Comment by noramyer** [comment]
looking at it

**Comment by rshar1** [comment]
Fixed in #58
