### ISSUE TITLE
keep track of users in each conversation

### ISSUE THREAD

**Issue by rshar1** [turtlefarmer/codeu_project_2017#6]
Currently, the server has no knowledge of which users are in each conversation.
In order to push new messages to the users in a given conversation, however, the server must know this information. 

My initial thoughts involve implementing a hashmap in the server, mapping conversation uuid's to a LinkedList containing the output streams for the users currently in the conversation.

**Comment by turtlefarmer** [comment]
Can you clarify on the reasoning for a linked-list vs just a list?

**Comment by rshar1** [comment]
I chose a linked list because the only time the list is needed is when sending out a new message to all the clients in the given conversation. As such, the iterator has to go through all the list elements anyways, so it would already have to run at linear time. 

List in Java is an interface so I'm going to assume you mean array list? 

The only concern I have about the linked list is removing a connection when user switches conversations.

**Comment by turtlefarmer** [comment]
Yeah sorry I meant ArrayList.

The best data structure to use here depends a lot on how you expect the user to use the app.  Are we going with a "user 1 can only be in 1 convo at a time" system?  Or is it more like slack where you belong in channels/chats and you receive messages for all of them.  How would the user switch between conversations if we're going with this model?  How are messages stored when user2 sends a message and user1 is offline?  Let's discuss this a bit in the slack with everyone and then come back to this.

**Comment by rshar1** [comment]
This has been taken care of in the pull request for the real time. #8
