### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by iamgreggarcia** [turtlefarmer/codeu_project_2017#7]
Possible solutions:

- [Travis CI](https://travis-ci.org/)

- [Jenkins](https://jenkins.io/)

My intuition is that if we decide to do continuous integration, we should go with Travis CI, for two reasons: 1) I already have some experience with it, and 2) it integrates nicely with GitHub (it shows whether or not your build is passing or not, and we can display this inside our repository README file)

**Comment by rshar1** [comment]
I looked into Travis CI and I think it would be good to use.

**Comment by iamgreggarcia** [comment]
I think so too. My goal is to get our fork running with Travis sometime this weekend. I'll need to add the travis.yml file and any additional configurations.

**Comment by iamgreggarcia** [comment]
So I'm still exploring this issue. The problem is in order to use Travis, we need to use one of three build tools: Maven, Gradle, or Ant. I looked at both maven and ant, but we would need to fundamentally change the project structure and run all the dependencies through their respective build files. It's feasible, but would require so more time to look at so I'm putting it on the back burner for the mean time.
